### ISSUE TITLE
SCTP does not work

### ISSUE THREAD

**Issue by edrimon** [nickvsnetworking/pyhss#170]
Changing transport to "SCTP", just does nothing. I just try with a single IP (SCTP non-multihoming). It seems there are not many things for this SCTP case in the documentation. Can you please help?

root@backup-server:~/pyhss-master/services# python3 diameterService.py

root@backup-server:~/pyhss-master/services#

**Comment by Kidwithservers** [comment]
I am also seeing this issue. Have you found any fixes yet?

**Comment by osmith42** [comment]
With current master and these options, sctp works for me:
```
hss:
  sctp:
    rtoMax: 5000
    rtoMin: 500
    rtoInitial: 1000
```

Closing.
